# Generated by Django 3.2.14 on 2022-07-24 21:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='posts/<django.db.models.fields.SlugField>')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='tags.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, main.models.CheckAgeMixin),
        ),
    ]
