# Generated by Django 4.1.1 on 2022-10-03 20:04

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_file",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to="images/posts/%Y/%m/%d"
            ),
        ),
    ]
