version: "3.9"
services:
  app:
    build: .
    ports:
      - "50000:5000"
    environment:
      - FLASK_DEBUG=1
    volumes:
      - .:/app
  db:
    image: "postgres"
    ports:
      - "50432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=admin
    volumes:
    - ./data/db:/var/lib/postgresql/data