# Generated by Django 4.1.1 on 2022-10-12 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToAdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(help_text="Rozwiń to co opisałeś w tytule"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Podaj swojego maila a poinformujemy Cię kiedy odpowiedź na Twoje pytanie będzie gotowa",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("realised", models.BooleanField(default=False)),
                (
                    "realised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_add_realisator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pozwoli nam to odpowiedzieć na pytanie w sposób zrozumiały dla Ciebie i odpowiedni do Twojego poziomu wiedzy",
                        related_name="to_add",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Do uzupełnienia",
                "verbose_name_plural": "Do uzupełnienia",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("published", models.BooleanField(default=False)),
                ("sponsored", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(auto_now=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "image_file",
                    sorl.thumbnail.fields.ImageField(
                        blank=True, null=True, upload_to="images/posts/%Y/%m/%d"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts_authors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts_editors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="tags.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posty",
            },
        ),
    ]
